package algorithms.centralityAlgorithms.closeness.formula;

public enum FormulaType {
	FORMULA_TYPE_STANDARD,
	FORMULA_TYPE_RECIPROCAL,
	FORMULA_TYPE_EXPONENTIAL,
	FORMULA_TYPE_WEIGHTED,
	FORMULA_TYPE_IV,
	FORMULA_TYPE_FOOTPRINT,
	FORMULA_TYPE_MONITOR_FOOTPRINT
}
